//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanGiay_Ver_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int product_id { get; set; }
        public int size { get; set; }
        public int users_id { get; set; }
        public int quantity { get; set; }
        public double price { get; set; }
        public double amount { get; set; }
        public string payment { get; set; }
        public System.DateTime date_order { get; set; }
        public Nullable<int> active { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
